### PR TITLE
#16 i18n puzzle resolved

### PR DESCRIPTION
**Pull request by palyuga**
This is a pull request for issue #16

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks, I'll find someone to review this PR soon

**Comment by dmarkov** [comment]
@yegor256 please review this one

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by dmarkov** [comment]
@yegor256 **16 mins** was added to your account, many thanks for your contribution!; added +16 to your rating, now it is equal to [+4891](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
