### PR TITLE
Remove extra parameters in Mojo

### LINKED ISSUE #25: Cease to use Jfrog Anno Mojo maven plugin and use normal maven xdoclet annotations
jcabi-ssl-maven-plugin can't be built with Java 8, because we use Jfrog Anno Mojo maven plugin, and it's not ready for Java8 (for details see #13).
It is [decided](https://github.com/jcabi/jcabi-ssl-maven-plugin/issues/13#issuecomment-71197569) to get rid of Jfrog Anno Mojo maven plugin and use normal maven xdoclet annotations.

(Jfrog Anno Mojo allows to use Java5-style annotations instead of writing them in javadoc comments.
We need to switch back to this comments option.)

You can find the plugin's occurrences in pom.xml by searching for `jfrog`.

### PR DESCRIPTION
**Pull request by Suseika**
Fixes #25

#34 was supposed to fix #25. #34 was merged, and then @wentwog showed there are errors in the code.

In #34 I mistakingly marked two extra fields as parameters. This PR removes that extra piece of javadoc.

### CODE REVIEW

**Comment by Suseika** [comment]
@dmarkov #34 was merged, but there still are issues with the code. Please review.

**Comment by dmarkov** [comment]
@suseika Thanks for your pull request, let me find someone who can review it

**Comment by dmarkov** [comment]
@yegor256 review this pls (it's a rather short pull request)

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 **16 mins** sent to your balance (ID `000-c48d7aa7`), many thanks! It took 24 hours and 31 mins.

review comments (c=1) added as a bonus

+16 to your rating, your total score is [+5885](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
