### PR TITLE
First attempt to fix the problem with failing tests.

### PR DESCRIPTION
**Pull request by dpisarenko**
Issue https://github.com/jcabi/jcabi-ssl-maven-plugin/issues/4

### CODE REVIEW

**Comment by dpisarenko** [comment]
@longtimeago I fixed the problems you reported. The new puzzle refers to issue https://github.com/jcabi/jcabi-ssl-maven-plugin/issues/11 .

**Comment by longtimeago** [comment]
@dpisarenko Thank you! Now it's good

**Comment by longtimeago** [comment]
@rultor good to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@longtimeago **24 mins** was added to your account, many thanks for your contribution!... +24 to your rating, your total score is [+1117](http://www.netbout.com/b/35024?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
