### PR TITLE
Add Javadoc badge with automatic version detection

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by dmarkov** [comment]
@valery1707 Many thanks for the PR, let me find a reviewer for it

**Comment by dmarkov** [comment]
@yegor256 pull request is rather short, review it please

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 Much appreciated! **16 mins** was added to your account, payment ID `000-7038d658`, time spent is 66 hours and 11 mins... extra minutes for review comments (c=1)... +16 to your rating, your total score is [+4335](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
